export const manualAdjustments = {
    'New York': [5, 0, false],
    'Michigan': [15, 20, false],
    'Florida': [25, 10, false],
    'Washington': [0, 0, false],
    'California': [0, 10, false],
    'Hawaii': [-20, 5, true],
    'Alaska': [5, -10, false],
    'Puerto Rico': [0, 10, false],
    'District of Columbia': [55, 45, true, -15, -15],
    'Vermont': [-40, -60, true, 10, 20],
    'New Hampshire': [-15, -70, true, 0, 0],
    'Maine': [0, 5, false],
    'Massachusetts': [50, -20, true, -25, 0],
    'Rhode Island': [50, 15, true, -15, -15],
    'Connecticut': [40, 30, true, -10, -15],
    'New Jersey': [35, 5, true, -15, -10],
    'Delaware': [60, 10, true, -15, -5],
    'Maryland': [95, 45, true, -15, -5],
    'Virginia': [0, 0, false],
    'North Carolina': [0, -5, false],
    'South Carolina': [0, 0, false],
    'Georgia': [5, 5, false],
    'Alabama': [5, 5, false],
    'Mississippi': [0, 5, false],
    'Louisiana': [-5, 5, false],
    'Texas': [0, 10, false],
    'Arkansas': [0, 0, false],
    'Missouri': [0, 0, false],
    'Iowa': [0, 0, false],
    'Wisconsin': [0, 0, false],
    'Minnesota': [0, 0, false],
    'North Dakota': [0, 0, false],
    'South Dakota': [0, 0, false],
    'Nebraska': [0, 0, false],
    'Kansas': [0, 0, false],
    'Oklahoma': [0, 10, false],
    'Montana': [0, 0, false],
    'Wyoming': [0, 10, false],
    'Colorado': [0, 0, false],
    'New Mexico': [0, 0, false],
    'Arizona': [0, 0, false],
    'Utah': [0, 10, false],
    'Idaho': [0, 15, false],
    'Nevada': [0, 10, false],
    'Oregon': [0, 0, false],
    'Kentucky': [0, 0, false],
    'Indiana': [0, 0, false],
    'Ohio': [0, 0, false],
    'Illinois': [0, 0, false],
    'Pennsylvania': [0, 0, false],
    'Tennessee': [0, 0, false],
    'West Virginia': [-7, 5, false]
};